version: '3'

services:
  proxy:
    image: charlesdalton/nginx-reverse-proxy
    ports:
      - '80:80'
  blog:
    image: ghost:alpine
    volumes:
      - ghost-data:/var/lib/ghost/content


volumes:
  ghost-data:
